// Generated by Wrangler by running `wrangler types --env-interface=CloudflareBindings`
// Regenerate with: bun run cf-typegen
interface CloudflareBindings {
	TALASH_DB: D1Database;
	TALASH_KV: KVNamespace;
	TALASH_STORAGE: R2Bucket;
	TALASH_QUEUE: Queue;
	TALASH_AI: Ai;
	AUTH_SERVICE: Fetcher;
	ENVIRONMENT: "development" | "staging" | "production";
	ALLOWED_ORIGINS: string;
	PUBLIC_R2_URL: string;
	JWT_SECRET: string;
}
